services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    depends_on:
      - mongo-seed

  mongo-seed:
    image: mongo:latest
    volumes:
      - ./data/posts.json:/datasets/posts.json
      - ./data/users.json:/datasets/users.json
      - ./data/resources.json:/datasets/resources.json
    command: mongoimport --host mongodb --db recursosEducativos --collection users --file /datasets/users.json --jsonArray &&
              mongoimport --host mongodb --db recursosEducativos --collection resources --file /datasets/resources.json --jsonArray &&
              mongoimport --host mongodb --db recursosEducativos --collection posts --file /datasets/posts.json --jsonArray